packages:
  - "backend"
  - "frontend"

injectWorkspacePackages: true

syncInjectedDepsAfterScripts:
  - build

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  mongodb-memory-server: true
  sharp: true
  unrs-resolver: true
  vue-demi: true